# Use root/example as user/password credentials
version: '3.7'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
    - .env
    volumes:
    - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  web-node:
    build: .
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env  
    depends_on:
      - db